import { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useChatStore } from '../store/chatStore'
import { useJobStore } from '../store/jobStore'
import { useAssessmentStore } from '../store/assessmentStore'
import { getScenario } from '../data/scenarios'
import { buildSystemPrompt } from '../prompts/systemPrompt'
import { buildAssessmentPrompt } from '../prompts/assessmentPrompt'
import { streamChatCompletion, formatMessagesForAPI } from '../services/deepseek'
import { parseAssessmentResult } from '../utils/assessmentParsing'
import { runAssessmentWithRetry } from '../utils/assessmentRetry'
import { buildAssessmentRecord } from '../utils/assessmentHistory'
import { useHistoryStore } from '../store/historyStore'
import { MessageBubble } from '../components/chat/MessageBubble'
import { ChatInput } from '../components/chat/ChatInput'
import { TimelineBar } from '../components/chat/TimelineBar'
import { TypingIndicator } from '../components/chat/TypingIndicator'
import { TaskSelector, type TaskOption } from '../components/chat/TaskSelector'
import { RoleNotification } from '../components/chat/RoleNotification'
import { IdleHint } from '../components/chat/IdleHint'
import { ColleagueDrawer } from '../components/chat/ColleagueDrawer'
import type { ChatMessage, TimelineStep } from '../types/chat'
import type { ScenarioPhase } from '../types/job'
import './ChatPage.css'

const TASK_ICONS: Record<string, string> = {
  'day1-task1': '📋', 'day1-task2': '💬', 'day1-task3': '📝',
  'day2-task1': '🤝', 'day2-task2': '✍️',
  'day3-task1': '🎨', 'day3-task2': '📊',
}

function randomizePhase(phase: ScenarioPhase): ScenarioPhase {
  if (!phase.variants || phase.variants.length === 0) return phase
  const useVariant = Math.random() > 0.5
  if (!useVariant) return phase
  const variant = phase.variants[Math.floor(Math.random() * phase.variants.length)]
  return { ...phase, ...variant }
}

/** 评估请求总次数上限：首次请求 + 1 次重试 */
const MAX_ASSESSMENT_ATTEMPTS = 2

/** 构造"跳过任务"的用户消息（模块级函数，事件回调中调用，避免渲染期纯度规则误报） */
function buildSkipMessage(phase: ScenarioPhase): ChatMessage {
  return {
    id: `skip-${Date.now()}`,
    role: 'user',
    content: `[用户跳过了本轮任务：${phase.title}，未作任何回复]`,
    timestamp: Date.now(),
  }
}

/** 构造普通用户消息（模块级函数，事件回调中调用）；autoGenerated 标记 AI 代答消息 */
function buildUserMessage(text: string, autoGenerated = false): ChatMessage {
  return {
    id: `user-${Date.now()}`,
    role: 'user',
    content: text,
    timestamp: Date.now(),
    ...(autoGenerated ? { autoGenerated: true } : {}),
  }
}

/** 构建某天的时间轴（阶段顺序即时间顺序） */
function buildDayTimeline(dayPhases: ScenarioPhase[]): TimelineStep[] {
  return dayPhases.map((p, i) => ({
    time: p.time,
    title: p.title,
    status: i === 0 ? 'active' as const : 'pending' as const,
  }))
}

/** 找到最后一条已启动阶段（⏰ 系统消息）对应的阶段索引；无则返回 -1 */
function findLastStartedPhaseIndex(
  messages: ChatMessage[],
  phases: ScenarioPhase[]
): number {
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i]
    if (msg.role !== 'system' || !msg.content.startsWith('⏰')) continue
    return phases.findIndex((p) => msg.content === `⏰ ${p.time} — ${p.title}`)
  }
  return -1
}

/** 根据 ⏰ 系统消息重建"已启动阶段"集合（内容与 activePhases 的 time/title 精确匹配） */
function rebuildStartedPhases(
  messages: ChatMessage[],
  phases: ScenarioPhase[]
): Set<number> {
  const started = new Set<number>()
  for (const msg of messages) {
    if (msg.role !== 'system' || !msg.content.startsWith('⏰')) continue
    const idx = phases.findIndex((p) => msg.content === `⏰ ${p.time} — ${p.title}`)
    if (idx >= 0) started.add(idx)
  }
  return started
}

/**
 * 单次评估请求：把回调式 streamChatCompletion 包装成 Promise。
 * 注意：result 必须在函数内部累积，否则第二次请求会拼接在第一次的错误内容后面。
 */
function requestAssessmentOnce(prompt: string, signal?: AbortSignal): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    let result = ''
    streamChatCompletion({
      messages: [{ role: 'user', content: prompt }],
      maxTokens: 4096,
      temperature: 0.2,
      signal,
      onChunk: (text) => { result += text },
      onDone: () => resolve(result),
      onError: (err) => reject(err),
    })
  })
}

export function ChatPage() {
  const navigate = useNavigate()
  const location = useLocation()
  const selectedJob = useJobStore((s) => s.selectedJob)
  const {
    messages, currentPhaseIndex, currentDay, timeline, activePhases,
    isLoading, isComplete, isSelectingTask, replyRequest,
    colleagueMessages, userMessageCount, addMessage, removeMessage,
    setLoading, setPhaseIndex, setTimeline, setActivePhases, setSelectingTask,
    setReplyRequest, setColleagueMessages,
    setComplete, incrementUserMessages, reset,
  } = useChatStore()
  const { setResult, setGenerating } = useAssessmentStore()

  // 存在未解决的回复请求（pending 或 retryable）：
  // 刷新后首次渲染可能是 pending + isLoading=false（effect 稍后才把 pending 改为 retryable），
  // 这段时间必须同样禁止发送/跳过，否则会覆盖 replyRequest。
  const hasUnresolvedReply = replyRequest !== null

  const [roleNotif, setRoleNotif] = useState({ visible: false, role: '', desc: '' })
  const [showIdleHint, setShowIdleHint] = useState(false)
  const [autoGenCount, setAutoGenCount] = useState(0)
  const [colleagueOpen, setColleagueOpen] = useState(false)
  const idleTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // 任务选择器的候选项：由 当前天剩余阶段 推导（不重复存储，刷新后自动恢复）
  const pendingTasks = useMemo<TaskOption[]>(() => {
    if (!isSelectingTask) return []
    const dayPhases = activePhases.filter((p) => p.day === currentDay)
    if (dayPhases.length === 0) return []
    const globalFirst = activePhases.indexOf(dayPhases[0])
    const localIndex = currentPhaseIndex - globalFirst
    return dayPhases.slice(localIndex + 1).map((p) => ({
      id: p.id,
      title: p.title,
      description: p.description,
      role: p.role,
      icon: TASK_ICONS[p.id] || '📌',
    }))
  }, [isSelectingTask, activePhases, currentPhaseIndex, currentDay])

  // 组件卸载时中止进行中的回复请求（SPA 离开 /chat 时取消上游，避免浪费 Token）。
  // StrictMode 兼容：幻影卸载的清理把 abort 延迟到宏任务，期间若已重挂载（新控制器接管）
  // 则跳过——不会误杀新挂载期的请求（含开场请求）。
  // 但请求可能使用幻影期创建的控制器（#1），因此真卸载时要中止"所有曾创建的控制器"。
  const replyAbortRef = useRef<AbortController | null>(null)
  const liveControllersRef = useRef<Set<AbortController>>(new Set())
  useEffect(() => {
    const controller = new AbortController()
    replyAbortRef.current = controller
    const liveControllers = liveControllersRef.current
    liveControllers.add(controller)
    return () => {
      const current = replyAbortRef.current
      setTimeout(() => {
        if (replyAbortRef.current === current) {
          // 真卸载：中止全部控制器（含 StrictMode 首挂载期被跳过的旧控制器）
          for (const c of liveControllers) c.abort()
          liveControllers.clear()
          replyAbortRef.current = null
        }
        // 幻影卸载（期间已重挂载）：不动，等最终真卸载时统一中止
      }, 0)
    }
  }, [])

  const messagesEndRef = useRef<HTMLDivElement>(null)
  const storeScenario = useJobStore((s) => s.scenarioConfig)
  // 场景配置在挂载时固定一次（原为 useRef，渲染期读取 ref 会被 react-hooks/refs 规则拦截）
  const [scenario] = useState(() => storeScenario || (selectedJob ? getScenario(selectedJob.id) : null))
  const initRef = useRef(false)
  // StrictMode 下 effect 挂载会双调用，用 ref 保证 generateNow 只触发一次评估
  const generateNowHandledRef = useRef(false)
  // 阶段数组在 store 中持久化（刷新恢复用）：逻辑侧用 ref 读写，渲染侧用 store 值
  const activePhasesRef = useRef<ScenarioPhase[]>([])
  const dayStartedRef = useRef(0)
  const startedPhasesRef = useRef<Set<number>>(new Set())

  // PLACEHOLDER_EFFECTS

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }
  useEffect(scrollToBottom, [messages, isLoading, isSelectingTask])

  const resetIdleTimer = () => {
    if (idleTimerRef.current) clearTimeout(idleTimerRef.current)
    // 隐藏提示的 setState 放到异步回调中，避免在 effect 内同步调用 setState
    setTimeout(() => setShowIdleHint(false), 0)
    idleTimerRef.current = setTimeout(() => setShowIdleHint(true), 120000)
  }

  useEffect(() => {
    if (!isLoading && !isComplete && !isSelectingTask && messages.length > 0) {
      resetIdleTimer()
    }
    return () => { if (idleTimerRef.current) clearTimeout(idleTimerRef.current) }
  }, [isLoading, isComplete, isSelectingTask, messages.length])

  // PLACEHOLDER_FUNCTIONS

  const showRoleNotification = (phase: ScenarioPhase) => {
    setRoleNotif({ visible: true, role: phase.role, desc: phase.roleDescription })
  }

  /**
   * 发送阶段 AI 消息（该阶段的用户消息已在 store 中，无需 extraMessages，避免请求体重复）。
   * 返回是否成功：失败时 replyRequest 进入 retryable，可由"重新获取回复"一键重试。
   * signal：卸载取消信号（开场/发送/重试均挂接；StrictMode 幻影卸载不会误杀，见 replyAbortRef 注释）。
   */
  const sendAIMessage = useCallback(async (
    phaseIndex: number,
    signal?: AbortSignal
  ): Promise<boolean> => {
    if (!scenario || !activePhasesRef.current.length) return false
    const phase = activePhasesRef.current[phaseIndex]
    if (!phase) return false
    const systemPrompt = buildSystemPrompt(scenario, phase)
    const currentMessages = useChatStore.getState().messages

    // Only send messages from the current phase (after the last system transition message)
    const lastSysIndex = currentMessages.map((m, i) => ({ m, i }))
      .filter(({ m }) => m.role === 'system' && m.content.startsWith('⏰'))
      .pop()?.i ?? 0
    const phaseMessages = currentMessages.slice(lastSysIndex + 1)

    const apiMessages = [
      { role: 'system', content: systemPrompt },
      ...formatMessagesForAPI(phaseMessages.filter((m) => m.role !== 'system')),
    ]

    setLoading(true)
    setReplyRequest({ phaseIndex, assistantMessageId: null, status: 'pending' })
    let content = ''
    const msgId = `ai-${Date.now()}`
    let added = false
    let succeeded = false

    await streamChatCompletion({
      messages: apiMessages,
      signal,
      onChunk: (text) => {
        content += text
        if (!added) {
          added = true
          addMessage({
            id: msgId, role: 'assistant', content,
            timestamp: Date.now(), scenarioRole: phase.role,
          })
          // 记录已写入的 assistant 消息 id（重试前删除残缺消息）
          setReplyRequest({ phaseIndex, assistantMessageId: msgId, status: 'pending' })
        } else {
          useChatStore.setState((state) => ({
            messages: state.messages.map((m) =>
              m.id === msgId ? { ...m, content } : m
            ),
          }))
        }
      },
      onDone: () => {
        succeeded = true
        setLoading(false)
        setReplyRequest(null) // 正常结束
      },
      onError: (err) => {
        console.error('Chat error:', err)
        succeeded = false
        setLoading(false)
        // 报错 → 可重试（保留 assistantMessageId 供重试时删除残缺回复）
        setReplyRequest({
          phaseIndex,
          assistantMessageId: added ? msgId : null,
          status: 'retryable',
        })
      },
    })
    return succeeded
  }, [scenario, addMessage, setLoading, setReplyRequest])

  const startPhase = useCallback((phaseIndex: number) => {
    if (!activePhasesRef.current.length) return
    const phase = activePhasesRef.current[phaseIndex]
    if (!phase) return
    if (startedPhasesRef.current.has(phaseIndex)) return
    startedPhasesRef.current.add(phaseIndex)
    addMessage({
      id: `sys-${Date.now()}`,
      role: 'system',
      content: `⏰ ${phase.time} — ${phase.title}`,
      timestamp: Date.now(),
    })
    sendAIMessage(phaseIndex, replyAbortRef.current?.signal)
  }, [addMessage, sendAIMessage])

  // PLACEHOLDER_HANDLERS

  const getDayPhases = () => activePhasesRef.current.filter((p) => p.day === currentDay)
  const getCurrentDayPhaseIndex = () => {
    const dayPhases = getDayPhases()
    const globalFirst = activePhasesRef.current.indexOf(dayPhases[0])
    return currentPhaseIndex - globalFirst
  }

  const handleSkipPhase = () => {
    if (hasUnresolvedReply) return // 存在未解决的回复请求时不允许跳过（含刷新后的 pending 首帧）
    const phase = activePhasesRef.current[currentPhaseIndex]
    if (phase) {
      addMessage(buildSkipMessage(phase))
    }
    showNextTaskOptions()
  }

  const showNextTaskOptions = () => {
    const dayPhases = getDayPhases()
    const localIndex = getCurrentDayPhaseIndex()
    const remaining = dayPhases.slice(localIndex + 1)
    if (remaining.length === 0) {
      if (currentDay >= 3) {
        setComplete()
        generateAssessment()
      } else {
        navigate('/day-complete')
      }
      return
    }
    // 候选项由 pendingTasks（推导）渲染，这里只需打开选择器
    setSelectingTask(true)
  }

  const handleTaskSelect = (task: TaskOption) => {
    setSelectingTask(false)
    const idx = activePhasesRef.current.findIndex((p) => p.id === task.id)
    if (idx === -1) return
    setPhaseIndex(idx)
    const phase = activePhasesRef.current[idx]
    showRoleNotification(phase)
    startPhase(idx)
  }

  const handleSend = async (text: string, autoGenerated = false) => {
    if (!scenario || isComplete || isSelectingTask || hasUnresolvedReply) return
    resetIdleTimer()
    const userMsg = buildUserMessage(text, autoGenerated)
    addMessage(userMsg)
    incrementUserMessages()

    const phase = activePhasesRef.current[currentPhaseIndex]
    if (!phase) return
    const newCount = userMessageCount + 1

    // 只有 AI 回复成功才推进流程：失败时用户通过"重新获取回复"重试，
    // 重试成功后若已达阈值再打开任务选择器（避免失败也提前推进）
    const succeeded = await sendAIMessage(currentPhaseIndex, replyAbortRef.current?.signal)
    if (succeeded && newCount >= phase.messageThreshold) {
      showNextTaskOptions()
    }
  }

  /** 一键重试失败的 AI 回复：删除残缺消息 → 用原 phaseIndex 重新请求（不新增用户消息） */
  const handleRetryReply = async () => {
    const req = useChatStore.getState().replyRequest
    if (!req || req.status !== 'retryable') return

    // 删除残缺的 assistant 消息（若有）
    if (req.assistantMessageId) {
      removeMessage(req.assistantMessageId)
    }

    const succeeded = await sendAIMessage(req.phaseIndex, replyAbortRef.current?.signal)
    if (succeeded) {
      // 重试成功后，若当前用户消息数已达到该阶段阈值，再打开任务选择器
      const phase = activePhasesRef.current[req.phaseIndex]
      const count = useChatStore.getState().userMessageCount
      if (phase && count >= phase.messageThreshold) {
        showNextTaskOptions()
      }
    }
  }

  const handleAutoGenerate = async () => {
    if (!scenario || isLoading || isComplete || isSelectingTask || hasUnresolvedReply) return
    setAutoGenCount((c) => c + 1)
    const phase = activePhasesRef.current[currentPhaseIndex]
    if (!phase) return

    const currentMessages = useChatStore.getState().messages
    const lastSysIndex = currentMessages.map((m, i) => ({ m, i }))
      .filter(({ m }) => m.role === 'system' && m.content.startsWith('⏰'))
      .pop()?.i ?? 0
    const phaseMessages = currentMessages.slice(lastSysIndex + 1)

    const genPrompt = `你是一个正在参加"${scenario.jobTitle}"岗位体验的优秀实习生。当前场景是"${phase.title} - ${phase.description}"。

根据以下对话上下文，请以实习生身份生成一条高质量的回复，要求：
- 表达清晰有条理，展现结构化思维
- 体现数据意识和量化思维
- 展现用户同理心和换位思考
- 有具体的行动方案和执行步骤
- 语气自然专业，像一个认真负责的实习生

对话上下文：
${phaseMessages.filter(m => m.role !== 'system').map(m => `[${m.role === 'user' ? '实习生' : phase.role}]: ${m.content}`).join('\n')}

请直接输出实习生的回复内容，不要加任何前缀或解释。`

    setLoading(true)
    let generatedText = ''

    await streamChatCompletion({
      messages: [{ role: 'user', content: genPrompt }],
      signal: replyAbortRef.current?.signal, // 代答请求同样挂接卸载取消
      onChunk: (text) => { generatedText += text },
      onDone: () => {
        setLoading(false)
        if (generatedText.trim()) {
          // 代答内容以"AI 代答"身份进入会话：气泡标注，评估不作为能力证据
          handleSend(generatedText.trim(), true)
        }
      },
      onError: () => setLoading(false),
    })
  }

  const generateAssessment = useCallback(async () => {
    if (!scenario) return
    setGenerating(true)
    setComplete()
    const allMsgs = useChatStore.getState().messages
    // 传入场景各阶段的 scoringDimensions：让评估证据贴合岗位任务（内置剧本/自定义 JD 场景均生效）
    const prompt = buildAssessmentPrompt(allMsgs, scenario.jobTitle, colleagueMessages, scenario.phases)

    const finishWithFallback = () => {
      setResult({
        overallScore: 0,
        jobFitPercentage: 0,
        dimensions: [],
        strengths: [],
        improvements: [],
        suggestions: ['评估报告生成失败，可能是网络波动或服务繁忙，请返回重新体验后再试。'],
        fitAdvice: '本次评估未能完成。',
      })
      setGenerating(false)
      navigate('/results')
    }

    // 最多尝试 MAX_ASSESSMENT_ATTEMPTS 次（首次请求 + 1 次重试）。
    // 解析/校验失败会重试；请求本身失败立即终止（语义见 runAssessmentWithRetry）。
    // 挂接卸载取消信号：离开 /chat 时评估请求同样被中止。
    let wasCancelled = false
    const parsed = await runAssessmentWithRetry(
      (p: string) => requestAssessmentOnce(p, replyAbortRef.current?.signal),
      parseAssessmentResult,
      prompt,
      MAX_ASSESSMENT_ATTEMPTS,
      (attempt, err) => {
        if (err) {
          if (err instanceof Error && err.message === '请求已取消') wasCancelled = true
          console.error(`[评估] 第 ${attempt} 次请求失败:`, err)
        } else {
          console.warn(`[评估] 第 ${attempt} 次解析/校验失败，${attempt < MAX_ASSESSMENT_ATTEMPTS ? '准备重试' : '已达最大尝试次数'}`)
        }
      }
    )

    if (parsed) {
      setResult(parsed)
      setGenerating(false)
      // 评估历史：仅合法结果入库（兜底报告不计入）；用 getState 避免引入订阅依赖
      useHistoryStore.getState().addRecord(
        buildAssessmentRecord({
          jobTitle: useJobStore.getState().selectedJob?.title || '岗位体验',
          result: parsed,
        })
      )
      setTimeout(() => navigate('/results'), 1500)
      return
    }

    // 用户已离开 /chat（请求被取消）：不跳转兜底报告，静默结束即可
    if (wasCancelled) {
      setGenerating(false)
      return
    }

    finishWithFallback()
  }, [scenario, colleagueMessages, navigate, setComplete, setGenerating, setResult])

  // 初始化/换天 effect：声明放在其引用的函数之后（react-hooks/immutability 要求先声明后使用）
  useEffect(() => {
    if (!selectedJob || !scenario) {
      navigate('/select')
      return
    }

    const generateNow = (location.state as { generateNow?: boolean } | null)?.generateNow
    if (generateNow) {
      // StrictMode 双调用保护：避免重复触发评估（重复 API 调用 + 重复历史记录）
      if (generateNowHandledRef.current) return
      generateNowHandledRef.current = true
      generateAssessment()
      return
    }

    const chatState = useChatStore.getState()
    const { messages: storedMessages, activePhases: storedPhases, sessionJobId: storedJobId } = chatState

    if (initRef.current) {
      // 本挂载内已初始化：仅处理跨天（组件保持挂载时 currentDay 变化）
      if (activePhasesRef.current.length === 0) return
      if (dayStartedRef.current === currentDay) return
      dayStartedRef.current = currentDay
      startedPhasesRef.current.clear()
      const dayPhases = activePhasesRef.current.filter((p) => p.day === currentDay)
      if (dayPhases.length > 0) {
        const firstPhaseOfDay = activePhasesRef.current.indexOf(dayPhases[0])
        setPhaseIndex(firstPhaseOfDay)
        setTimeline(buildDayTimeline(dayPhases))
        showRoleNotification(dayPhases[0])
        startPhase(firstPhaseOfDay)
      }
      return
    }

    initRef.current = true

    // ---- 恢复路径：刷新后继续进行中的会话 ----
    // 条件：存在消息与阶段数组、会话属于当前岗位、最后启动的阶段属于当前天
    //（命中时不 reset、不重新随机化、不重发开场消息，直接沿用 store 中的数据）
    const lastStartedIndex = findLastStartedPhaseIndex(storedMessages, storedPhases)
    const isRestorable =
      storedMessages.length > 0 &&
      storedPhases.length > 0 &&
      storedJobId === selectedJob.id &&
      lastStartedIndex >= 0 &&
      storedPhases[lastStartedIndex].day === currentDay

    if (isRestorable) {
      activePhasesRef.current = storedPhases
      dayStartedRef.current = currentDay
      startedPhasesRef.current = rebuildStartedPhases(storedMessages, storedPhases)
      // 刷新中断检测：pending 的回复请求 → 标记为可重试（不靠消息角色推测；
      // 收到部分 chunk 时最后一条可能是 assistant，但仍算中断）
      if (chatState.replyRequest?.status === 'pending') {
        chatState.setReplyRequest({ ...chatState.replyRequest, status: 'retryable' })
      }
      return
    }

    // ---- 全新开始或跨天：重置本天会话 ----
    // 仅当是同一岗位的既有会话（跨天）才沿用已持久化的随机化结果；
    // 换岗/重选岗位时 storedPhases 属于旧岗位，必须重新随机化
    dayStartedRef.current = currentDay
    startedPhasesRef.current.clear()
    reset()
    chatState.setSessionJobId(selectedJob.id)

    const phases = (storedJobId === selectedJob.id && storedPhases.length > 0)
      ? storedPhases
      : scenario.phases.map(randomizePhase)
    activePhasesRef.current = phases
    setActivePhases(phases)

    const dayPhases = phases.filter((p) => p.day === currentDay)
    if (dayPhases.length === 0) return
    const firstPhaseOfDay = phases.indexOf(dayPhases[0])
    setPhaseIndex(firstPhaseOfDay)
    setTimeline(buildDayTimeline(dayPhases))
    showRoleNotification(dayPhases[0])
    startPhase(firstPhaseOfDay)
  }, [addMessage, currentDay, generateAssessment, location.state, navigate, reset, scenario, selectedJob, setActivePhases, setPhaseIndex, setTimeline, startPhase])

  if (!scenario) return null
  const currentPhase = activePhases[currentPhaseIndex]

  // PLACEHOLDER_RENDER

  return (
    <div className="chat-page">
      <RoleNotification
        visible={roleNotif.visible}
        role={roleNotif.role}
        description={roleNotif.desc}
        onHide={() => setRoleNotif((r) => ({ ...r, visible: false }))}
      />
      <IdleHint
        visible={showIdleHint}
        onDismiss={() => setShowIdleHint(false)}
      />
      <div className="chat-header">
        <h2>{scenario.jobTitle}的一天 · Day {currentDay}</h2>
        <span className="chat-status">
          {isComplete
            ? '体验完成，正在生成评估...'
            : `当前：${currentPhase?.title || ''}`}
        </span>
        <button
          className="chat-exit-btn"
          onClick={() => navigate('/select')}
          title="退回岗位选择页面"
        >
          <span className="chat-exit-icon">✕</span>
          <span className="chat-exit-text">退回岗位选择</span>
        </button>
      </div>
      <TimelineBar steps={timeline} />
      <div className="chat-messages">
        {messages.filter((m) => m.id).map((msg) => (
          <MessageBubble
            key={msg.id}
            role={msg.role}
            content={msg.content}
            scenarioRole={msg.scenarioRole}
            autoGenerated={msg.autoGenerated}
          />
        ))}
        {isLoading && <TypingIndicator />}
        {isSelectingTask && (
          <TaskSelector tasks={pendingTasks} onSelect={handleTaskSelect} />
        )}
        <div ref={messagesEndRef} />
      </div>
      <div className="chat-bottom-bar">
        <ChatInput
          onSend={handleSend}
          onAutoGenerate={handleAutoGenerate}
          showQuickSend={autoGenCount >= 2}
          disabled={isLoading || isComplete || isSelectingTask || hasUnresolvedReply}
        />
        {replyRequest?.status === 'retryable' && (
          <div className="reply-retry-bar">
            <span>回复获取失败，请重试</span>
            <button className="reply-retry-btn" onClick={handleRetryReply}>
              重新获取回复
            </button>
          </div>
        )}
        {!isComplete && !isSelectingTask && (
          <>
            <button
              className="colleague-btn"
              onClick={() => setColleagueOpen(true)}
              disabled={isLoading}
            >
              👩‍💼 问同事
            </button>
            <button
              className="skip-btn"
              onClick={handleSkipPhase}
              disabled={isLoading || hasUnresolvedReply}
            >
              跳过本轮
            </button>
          </>
        )}
      </div>
      <ColleagueDrawer
        open={colleagueOpen}
        onClose={() => setColleagueOpen(false)}
        phaseTitle={currentPhase?.title || ''}
        phaseDescription={currentPhase?.description || ''}
        background={scenario.background}
        messages={colleagueMessages}
        onMessagesChange={setColleagueMessages}
        getAbortSignal={() => replyAbortRef.current?.signal}
      />
    </div>
  )
}
