import './MessageBubble.css'

interface Props {
  role: 'system' | 'assistant' | 'user'
  content: string
  scenarioRole?: string
  /** AI 代答生成的用户消息：气泡上方显示"AI 代答"标签 */
  autoGenerated?: boolean
}

export function MessageBubble({ role, content, scenarioRole, autoGenerated }: Props) {
  return (
    <div className={`message-bubble ${role}`}>
      {role === 'assistant' && scenarioRole && (
        <span className="scenario-role">{scenarioRole}</span>
      )}
      {role === 'system' && (
        <span className="scenario-role">系统</span>
      )}
      {role === 'user' && autoGenerated && (
        <span className="auto-gen-label">AI 代答</span>
      )}
      <div className="bubble-content">
        {content.split('\n').map((line, i) => (
          <p key={i}>{line || ' '}</p>
        ))}
      </div>
    </div>
  )
}
