import { describe, it, expect } from 'vitest'
import { buildAssessmentPrompt } from './assessmentPrompt'
import type { ChatMessage } from '../types/chat'

/** 构造一条阶段开始消息（system，⏰ 前缀用于统计总阶段数） */
function phaseMessage(title: string): ChatMessage {
  return {
    id: `sys-${title}`,
    role: 'system',
    content: `⏰ 09:00 — ${title}`,
    timestamp: 0,
  }
}

/** 构造一条"跳过任务"用户消息（[用户跳过了本轮任务 前缀用于统计跳过数） */
function skipMessage(title: string): ChatMessage {
  return {
    id: `skip-${title}`,
    role: 'user',
    content: `[用户跳过了本轮任务：${title}，未作任何回复]`,
    timestamp: 0,
  }
}

/** 构造一条正常用户消息 */
function normalMessage(text: string): ChatMessage {
  return {
    id: `user-${text}`,
    role: 'user',
    content: text,
    timestamp: 0,
  }
}

describe('buildAssessmentPrompt 跳过惩罚规则', () => {
  it('全部跳过：触发严重警告和全部跳过限制', () => {
    const messages = [
      phaseMessage('任务一'),
      skipMessage('任务一'),
      phaseMessage('任务二'),
      skipMessage('任务二'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    expect(prompt).toContain('严重警告')
    expect(prompt).toContain('不得超过10分')
    expect(prompt).toContain('strengths应为空数组')
    expect(prompt).toContain('所有维度评分不得超过15分')
    expect(prompt).toContain('岗位适配度(jobFitPercentage)不得超过10')
    expect(prompt).toContain('evidence必须注明')
  })

  it('部分跳过：包含"跳过任务惩罚规则"，但不包含"跳过了全部"', () => {
    const messages = [
      phaseMessage('任务一'),
      normalMessage('任务一我完成了。'),
      phaseMessage('任务二'),
      skipMessage('任务二'),
      phaseMessage('任务三'),
      normalMessage('任务三也完成了。'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    expect(prompt).toContain('跳过任务惩罚规则')
    expect(prompt).not.toContain('跳过了全部')
  })

  it('没有跳过：不包含任何跳过惩罚规则', () => {
    const messages = [
      phaseMessage('任务一'),
      normalMessage('我完成了任务一。'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    expect(prompt).not.toContain('严重警告')
    expect(prompt).not.toContain('跳过任务惩罚规则')
    expect(prompt).not.toContain('跳过了全部')
  })
})

describe('buildAssessmentPrompt AI 代答标记', () => {
  /** 构造一条 AI 代答用户消息 */
  function autoGenMessage(text: string): ChatMessage {
    return { ...normalMessage(text), autoGenerated: true }
  }

  it('存在代答：对话记录标注"不作为能力证据"并含 AI代答说明', () => {
    const messages = [
      phaseMessage('任务一'),
      autoGenMessage('AI生成的回复'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    expect(prompt).toContain('[实习生(AI代答，不作为能力证据)]: AI生成的回复')
    expect(prompt).toContain('AI代答说明')
    expect(prompt).toContain('严禁作为评分证据')
    // 手打消息仍为普通"实习生"标记
    expect(prompt).not.toContain('[实习生]: AI生成的回复')
  })

  it('全部为代答且无本人输入：触发"未实质参与"限制（与全部跳过同级惩罚）', () => {
    const messages = [
      phaseMessage('任务一'),
      autoGenMessage('代答一'),
      phaseMessage('任务二'),
      autoGenMessage('代答二'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    expect(prompt).toContain('仅使用AI代答，无实际行为证据')
    expect(prompt).toContain('所有维度评分不得超过15分')
    expect(prompt).toContain('strengths应为空数组')
  })

  it('代答 + 本人输入：正常评分，代答仅标注不作证据', () => {
    const messages = [
      phaseMessage('任务一'),
      normalMessage('这是我的真实回复。'),
      autoGenMessage('AI代答内容'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    expect(prompt).toContain('AI代答说明')
    expect(prompt).toContain('[实习生(AI代答，不作为能力证据)]: AI代答内容')
    expect(prompt).toContain('[实习生]: 这是我的真实回复。')
    expect(prompt).not.toContain('仅使用AI代答')
    expect(prompt).not.toContain('所有维度评分不得超过15分')
  })

  it('跳过消息不带代答标记：跳过逻辑不受影响', () => {
    const messages = [
      phaseMessage('任务一'),
      skipMessage('任务一'),
      phaseMessage('任务二'),
      autoGenMessage('代答内容'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    // 跳过仍按跳过处理（部分跳过规则），代答单独标注
    expect(prompt).toContain('跳过任务惩罚规则')
    expect(prompt).toContain('AI代答说明')
    expect(prompt).toContain('[用户跳过了本轮任务：任务一，未作任何回复]')
  })

  it('无代答消息：不包含 AI代答说明', () => {
    const messages = [
      phaseMessage('任务一'),
      normalMessage('普通回复。'),
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生')

    expect(prompt).not.toContain('AI代答')
  })
})

describe('buildAssessmentPrompt 岗位证据侧重（scoringDimensions）', () => {
  const salesPhases = [
    { title: '晨会分配客户', scoringDimensions: ['沟通表达', '目标导向', '执行落地'] },
    { title: '客户沟通', scoringDimensions: ['客户沟通', '需求挖掘', '抗压能力'] },
  ]

  it('传入场景阶段：包含场景侧重维度与标准维度任务对应', () => {
    const messages = [
      phaseMessage('任务一'),
      normalMessage('我完成了。'),
    ]

    const prompt = buildAssessmentPrompt(messages, '销售代表', undefined, salesPhases)

    // 场景侧重：非标准维度（客户沟通/目标导向等）按任务列出
    expect(prompt).toContain('岗位证据侧重')
    expect(prompt).toContain('目标导向：晨会分配客户')
    expect(prompt).toContain('客户沟通：客户沟通')
    expect(prompt).toContain('需求挖掘：客户沟通')
    // 标准维度 → 任务对应
    expect(prompt).toContain('维度与任务对应')
    expect(prompt).toContain('沟通表达 → 晨会分配客户')
    expect(prompt).toContain('执行落地 → 晨会分配客户')
  })

  it('同一维度出现在多个任务：任务去重列出', () => {
    const messages = [
      phaseMessage('任务一'),
      normalMessage('我完成了。'),
    ]
    const phases = [
      { title: '晨会任务', scoringDimensions: ['沟通表达', '执行落地'] },
      { title: '今日汇报', scoringDimensions: ['沟通表达', '数据敏感度'] },
    ]

    const prompt = buildAssessmentPrompt(messages, '运营实习生', undefined, phases)

    expect(prompt).toContain('沟通表达：晨会任务、今日汇报')
    expect(prompt).toContain('沟通表达 → 晨会任务、今日汇报')
    expect(prompt).toContain('执行落地 → 晨会任务')
    // 无对应任务的标准维度（问题拆解/用户同理心/优先级判断/协作与求助）不列出
    expect(prompt).not.toContain('问题拆解 →')
  })

  it('不传场景阶段：不包含证据侧重段（兼容旧调用）', () => {
    const messages = [
      phaseMessage('任务一'),
      normalMessage('我完成了。'),
    ]

    const prompt = buildAssessmentPrompt(messages, '销售代表')

    expect(prompt).not.toContain('岗位证据侧重')
    expect(prompt).not.toContain('维度与任务对应')
  })
})
